### PR TITLE
exploring wins with nflfastR

### PR DESCRIPTION
**Pull request by austinryan11**
Adding exploring wins with nflfastR post

### CODE REVIEW

**Comment by mrcaseb** [comment]
Hey @austinryan11 looks better now, thanks!
However, it looks like you forgot to tweak the metadata. I am missing the toc, the repo_url and the categories
```yaml
---
title: "Exploring Wins with nflfastR"
description: |
  Looking at what metrics are important for predicting wins. Creating expected season win totals and comparing to reality.
author:
  - name: Austin Ryan | @packeRanalytics
    url: https://twitter.com/packeRanalytics
date: 08-23-2020
output:
  distill::distill_article:
    self_contained: false
---
```

Maybe like this
```yaml
---
title: "Exploring Wins with nflfastR"
description: |
  Looking at what metrics are important for predicting wins. Creating expected season win totals and comparing to reality.
author:
  - name: Austin Ryan | @packeRanalytics
    url: https://twitter.com/packeRanalytics
date: 08-23-2020
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
repository_url: "https://github.com/mrcaseb/open-source-football"
categories:
  - Tidymodels
  - Figures
  - nflfastR
---
```

I have also noticed you have manually set the plot dpi to 200 although we require 300 and set it in the main options chunk.
And I am wondering why you are excluding all of your code? Sharing the code is the idea of the posts...

**Comment by guga31bb** [comment]
I actually think not showing code is totally fine and makes sense for the
articles type pieces so the focus is on the content. People can still see
the code on github if they want

**Comment by austinryan11** [comment]
Hello! I have updated the metadata and removed the references to dpi = 200. I also added a sentence to note code is intentionally excluded but available in the rmd file on github. I was thinking I would have some content that is geared towards fans interested in reading about analytics but have no interest in programming. Then some content that are more how-to guides that would walk through the code in the post.

**Comment by guga31bb** [comment]
> Hello! I have updated the metadata and removed the references to dpi = 200. I also added a sentence to note code is intentionally excluded but available in the rmd file on github. I was thinking I would have some content that is geared towards fans interested in reading about analytics but have no interest in programming. Then some content that are more how-to guides that would walk through the code in the post.

Yep I think this makes sense. The post is up on the site now, thanks again!

**Pull request merged**
