### PR TITLE
Initial commit of post materials

### PR DESCRIPTION
**Pull request by richjand**
Added materials for post. Hope I didn't mess anything up along the way!

### CODE REVIEW

**Comment by guga31bb** [comment]
Thank you, this looks great and I'm excited to put this up!

Looks like there is one conflicting file in the pull request (docs/sitemap.xml). To fix this, please run `source("https://raw.githubusercontent.com/mrcaseb/open-source-football/master/_update_con_files.R")` as instructed [here](https://www.opensourcefootball.com/contributing.html) and then commit & push the updated files. This should resolve the merge conflict and allow us to put it up. Thanks!

**Comment by mrcaseb** [comment]
Ooooh, very excited to see this one!

**Comment by richjand** [comment]
Thanks guys. Really appreciate the work you put into the site and nflfastR. Hopefully things work now.

**Comment by guga31bb** [comment]
Thank you for the submission, really cool post! 

I noticed that the hyperlink clicking on your name at the top of the post is broken- I think adding http:// as a prefix would fix it. Not a big deal either way but if you do want to fix, it would just take fixing, re-knitting and submitting a new PR. Completely up to you.

**Pull request merged**
