### PR TITLE
Era adjusted qb elo rankings

### PR DESCRIPTION
**Pull request by greerreNFL**
Initial post for using Elo to rank and compare QBs across era

### CODE REVIEW

**Comment by guga31bb** [comment]
Thanks for the submission @greerreNFL! Have you tried pressing "Knit" in the .Rmd file? There should be a lot more files associated with each post. So either you haven't knitted or didn't push all the files that were created.

Thanks!

**Comment by mrcaseb** [comment]
I tried to knit it and got an error with a message no really saying something. But I was able to fix it. (Problem in the metadata). However, some plots didn't look good on my machine so I didn't push it. 
But if it is ok to you @greerreNFL I will push at least the minor fixes into your branch in about 30 mins

**Comment by mrcaseb** [comment]
Okay, I just took the liberty of fixing a few things. 

But it still appears to not render the plots correctly, at least on my machine 
image

**Comment by greerreNFL** [comment]
Thanks for taking a look! Everything looked OK in RStudio, but I can trouble shoot on my end. 

@guga31bb - totally new to both Git and distill, so very likely an easy to fix mistake on my end. I'll take a look at this too!

**Comment by mrcaseb** [comment]
All right I have added this code chunk to supress warnings revealing your username on your local machine @greerreNFL. 
```r
{python, include=FALSE}
# some of the plot chunks printed a warning that revealed the path to the local 
# Python installation including username. This chunk suppresses those warnings.
import warnings
warnings.filterwarnings('ignore')
```
Also tweaked the size of the figures as some aces lables were cutted and set the Manning, Brady, and Brees plot as the preview plot.

I'll wait for your ok before we merge this in as I didn't ask you if I am allowed to do this stuff

**Comment by greerreNFL** [comment]
Appreciated! Yep, good to merge! Thank you

**Pull request merged**
