### PR TITLE
finalize post

### PR DESCRIPTION
**Pull request by mikeirene**
Post on creating an expected field goals model using data from nflfastR

### CODE REVIEW

**Comment by guga31bb** [comment]
The .Rmd looks good. Please open it in RStudio and press "Knit" at the top to create all the necessary files, and then push them. There should be at least 15+ files in the "Files changed" tab above here.

**Comment by guga31bb** [comment]
There should be a lot more files associated with your post. Please commit and push them. Once you do it successfully, you'll see a lot more files showing up here 
image

**Comment by mikeirene** [comment]
Thanks for the feedback. Sorry for the back and forth, I'm new to github and have used R, but haven't used RMD much. I'm pressing Knit, but the additional files aren't showing up

**Comment by guga31bb** [comment]
No problem, I promise it gets easier after the first time!

Is there an error message showing up somewhere? I'm guessing something is going wrong if knit isn't generating additional files.

**Comment by mikeirene** [comment]
I get some warning messages, but no specific error message:
Capture

The html file pops up at the end and previews correctly though.

**Comment by guga31bb** [comment]
Hmm so if the html file pops up then there *should* be that file and others to push

**Comment by guga31bb** [comment]
Okay, I think we're almost set, thank you. One more small request and sorry I didn't catch this earlier. Please use 

> repository_url: "https://github.com/mrcaseb/open-source-football"

In that section at the top of the .Rmd instead of what you have. You'll need to re-knit and re-push.

**Pull request merged**
