### PR TITLE
Exploring wins with nflscrap r

### PR DESCRIPTION
**Pull request by austinryan11**
Add packeRanalytics wins

### CODE REVIEW

**Comment by guga31bb** [comment]
Is this intended to be a new article? All I can see here is the one that was already submitted.

**Comment by austinryan11** [comment]
Sorry this https://github.com/austinryan11/open-source-football/tree/master/_posts/2020-08-22-exploring-wins is intended to be a new article.  I must not be pushing the correct things.

**Comment by guga31bb** [comment]
1. Click on this
image

2. Check the files
image

So there's only 3 files and they're related to the last one.

My suggestion would be to [start over from this stage](https://mrcaseb.github.io/open-source-football/contributing.html#fork-the-repo), fork the repo again, start a new project in RStudio using the forked repo, create a new post (`distill::create_post("Title of your post")`), put your new .Rmd in there, knit, and push all the files. When you knit and push all the files related to the post, there should be 20+ files that end up in the pull request.

**Comment by austinryan11** [comment]
Thank you. I deleted the first repository I forked to, started a new project, and all appears well. See exploring wins with nflfastR #29 that has 22 files.

**Comment by guga31bb** [comment]
Great! Will close this and one of us will take a look at the new one tomorrow. At a quick glance, it looks good!

**Pull request closed without merging**
