### PR TITLE
New Article - Goldberg

### PR DESCRIPTION
**Pull request by gberg1303**
Wrote a quick article about merging 538 and ESPN game predictions with nflfastR.

### CODE REVIEW

**Comment by guga31bb** [comment]
Looks good! Looks like there's a conflicting file so please run `source("https://raw.githubusercontent.com/mrcaseb/open-source-football/master/_update_con_files.R")` as [instructed here](https://www.opensourcefootball.com/contributing.html) and push the updated file(s).

If it works successfully, this notice in the pull request will go away
image

**Comment by gberg1303** [comment]
I think we're good to go!

**Comment by mrcaseb** [comment]
Just saw the TOC is missing. Sorry, little late.

**Comment by mrcaseb** [comment]
Maybe not that important in this article as I am seeing only two headers.

**Comment by gberg1303** [comment]
Oh yeah, I didn't intend for there to be a TOC. Just something to break up the two bits as people were reading. Thanks for the catch though!

**Pull request merged**
