### PR TITLE
Article from Puntalytics

### PR DESCRIPTION
**Pull request by dennisbrookner**
Hey OSF team,

Excited to be writing an article here!  Let us know if there are any issues/concerns, either with formatting or with content.

### CODE REVIEW

**Comment by guga31bb** [comment]
Looks great, thanks! I'm not sure what these merge conflicts are so will need to wait for @mrcaseb to take a look.

**Comment by dennisbrookner** [comment]
Thanks!!

I'm also not sure what's up with the conflicts; the .DS_Store files are usually excluded via .gitignore, but that's not happening here for some reason, and I'm not totally confident that they could just be deleted.

**Comment by guga31bb** [comment]
1. The two .DS_Store files can be safely removed
2. Please run `source("https://raw.githubusercontent.com/mrcaseb/open-source-football/master/_update_con_files.R")` [as mentioned here](https://www.opensourcefootball.com/contributing.html) to fix the other two merge conflicts
3. Once you do 1 and 2, commit and push and it *should* get rid of all the merge conflicts

Thank you!

**Comment by dennisbrookner** [comment]
Looks like it's all set!

**Pull request merged**
