### PR TITLE
committing penalty epa post

### PR DESCRIPTION
**Pull request by JackLich10**
An analysis of penalties and penalty EPA (also looking at some penalties in Seahawks @ Cardinals just to tilt Ben). Thanks for maintaining the site and the database, you guys are the best!

### CODE REVIEW

**Comment by mrcaseb** [comment]
Thanks @JackLich10. Looks good to merge

**Comment by mrcaseb** [comment]
The post is online now but I had to reknit it because the page was empty. Could you check your installed version of distill @JackLich10 by running the following line?

```r
paste0("You are running distill v", utils::packageVersion("distill"))
```

If it's < v1.0 I ask you to update distill as I think this might be the problem (not sure though)

**Comment by JackLich10** [comment]
paste0("You are running distill v", utils::packageVersion("distill"))
[1] "You are running distill v1.1"

I think it's the latest version so I'm not sure that's the problem. The article looks right on the site though.

**Comment by JackLich10** [comment]
Ok, so I re-knit and a bunch of files showed up to push. I guess something happened the first time I knit that made these files not show up. So the problem was on my end but thanks for fixing it.

**Comment by mrcaseb** [comment]
Ah ok good to know. Thanks for the feedback!

**Pull request merged**
