### PR TITLE
upload

### PR DESCRIPTION
**Pull request by adriancm93**

### CODE REVIEW

**Comment by guga31bb** [comment]
Yesss very excited about this, thank you! 

It looks like this doesn't include all the needed files, so please press the "Knit" button in RStudio and push all the files that it creates. There should be something like 15-20 files in the "Files changed" tab on top.

**Comment by mrcaseb** [comment]
If you push the "knit" button the RStudio browser will try to preview your post. If it shows an empty page please push "open in browser" at the top. You should see your post than. Please check if your referenced urls are working. I think they won't get auto-linked in the moment.

**Comment by adriancm93** [comment]
Thank you both for your instructions and pointers. I'll try again this evening.

**Comment by adriancm93** [comment]
I am having an issue. When I try to knit, it tells me that the directory does not exist (even tho it does exist) when I copy and paste the path in a file explorer it works:

**This happens at the end of the process.**

Error: The specified directory 'C:/Users/adrian/Documents/open-source-football

**Another example:**
"cannot create dir 'individual-expected-completion-using-logistic-generalized-additive-mixed-models_files\figure-html5', reason 'No such file or directory'"

Not sure what could be the issue here. I've been googling with not much luck. Any idea?

**Comment by guga31bb** [comment]
After talking to Adrian I knitted and merged in https://github.com/mrcaseb/open-source-football/pull/45

**Pull request closed without merging**
